import type { MilitaryBranch } from "@/lib/types/database";

type RankOption = { value: string; label: string };

export const RANKS: Record<MilitaryBranch, RankOption[]> = {
  USAF: [
    { value: "2Lt", label: "2Lt - Second Lieutenant" },
    { value: "1Lt", label: "1Lt - First Lieutenant" },
    { value: "Capt", label: "Capt - Captain" },
    { value: "Maj", label: "Maj - Major" },
    { value: "Lt Col", label: "Lt Col - Lieutenant Colonel" },
    { value: "Col", label: "Col - Colonel" },
    { value: "Brig Gen", label: "Brig Gen - Brigadier General" },
    { value: "Maj Gen", label: "Maj Gen - Major General" },
    { value: "Lt Gen", label: "Lt Gen - Lieutenant General" },
    { value: "Gen", label: "Gen - General" },
  ],
  USN: [
    { value: "ENS", label: "ENS - Ensign" },
    { value: "LTJG", label: "LTJG - Lieutenant Junior Grade" },
    { value: "LT", label: "LT - Lieutenant" },
    { value: "LCDR", label: "LCDR - Lieutenant Commander" },
    { value: "CDR", label: "CDR - Commander" },
    { value: "CAPT", label: "CAPT - Captain" },
    { value: "RDML", label: "RDML - Rear Admiral Lower Half" },
    { value: "RADM", label: "RADM - Rear Admiral" },
    { value: "VADM", label: "VADM - Vice Admiral" },
    { value: "ADM", label: "ADM - Admiral" },
  ],
  USA: [
    { value: "WO1", label: "WO1 - Warrant Officer 1" },
    { value: "CW2", label: "CW2 - Chief Warrant Officer 2" },
    { value: "CW3", label: "CW3 - Chief Warrant Officer 3" },
    { value: "CW4", label: "CW4 - Chief Warrant Officer 4" },
    { value: "CW5", label: "CW5 - Chief Warrant Officer 5" },
    { value: "2LT", label: "2LT - Second Lieutenant" },
    { value: "1LT", label: "1LT - First Lieutenant" },
    { value: "CPT", label: "CPT - Captain" },
    { value: "MAJ", label: "MAJ - Major" },
    { value: "LTC", label: "LTC - Lieutenant Colonel" },
    { value: "COL", label: "COL - Colonel" },
    { value: "BG", label: "BG - Brigadier General" },
    { value: "MG", label: "MG - Major General" },
    { value: "LTG", label: "LTG - Lieutenant General" },
    { value: "GEN", label: "GEN - General" },
  ],
  USMC: [
    { value: "2ndLt", label: "2ndLt - Second Lieutenant" },
    { value: "1stLt", label: "1stLt - First Lieutenant" },
    { value: "Capt", label: "Capt - Captain" },
    { value: "Maj", label: "Maj - Major" },
    { value: "LtCol", label: "LtCol - Lieutenant Colonel" },
    { value: "Col", label: "Col - Colonel" },
    { value: "BGen", label: "BGen - Brigadier General" },
    { value: "MajGen", label: "MajGen - Major General" },
    { value: "LtGen", label: "LtGen - Lieutenant General" },
    { value: "Gen", label: "Gen - General" },
  ],
  USCG: [
    { value: "ENS", label: "ENS - Ensign" },
    { value: "LTJG", label: "LTJG - Lieutenant Junior Grade" },
    { value: "LT", label: "LT - Lieutenant" },
    { value: "LCDR", label: "LCDR - Lieutenant Commander" },
    { value: "CDR", label: "CDR - Commander" },
    { value: "CAPT", label: "CAPT - Captain" },
  ],
};
